### ISSUE TITLE
Is there a way to create a single PDF out of all pages ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [abeMedia/jekyll-pdf#16]
Is there a way to create a single PDF out of all pages ?

**Comment by abemedia** [comment]
Yes there is. Just create a single template that gets all the posts e.g.

```liquid
{% for post in site.posts %}
<!-- post template here -->
{% endfor %}
```
You can also do this for HTML pages using the variable `{{ site.html_pages }}`.
