### ISSUE TITLE
Build issue : Digest gem not accessible anymore

### ISSUE THREAD

**Issue by pbelabbes** [abeMedia/jekyll-pdf#20]
RubyGem.org : "The gem _digest_ is no longer accessible, as the name was in the reserved namespace we've locked off -- it was only in the search results by accident, and we no longer are able to provide access to it via rubygems.org. I apologize for any disruption this has caused you!"

 
[discussion](http://help.rubygems.org/discussions/problems/31508-gem-install-digest-access-denied
)

**Comment by iamsebastian** [comment]
Until the PR of @m1racoli is merged, add this to your `Gemfile`:
```gem
gem 'jekyll-pdf', :git => 'git://github.com/m1racoli/jekyll-pdf', :branch => 'fix-digest-gem'
```

**Comment by benfrick** [comment]
This worked for me. Thanks @iamsebastian

**Comment by harsh183** [comment]
@iamsebastian Give that it's been several months. Do you think it's worth making a fork for this repo?

**Comment by hoijui** [comment]
there were severel forks fixing the same issue. I made one to serve as the official one. see here: https://github.com/abeMedia/jekyll-pdf/issues/24

**Comment by feluelle** [comment]
You can now use this repo `gem 'jekyll-pdf', :git => 'https://github.com/abeMedia/jekyll-pdf'` to get the latest code since it is merged into master.
